package com.example.gasmobileclient


const val CONFIGURATION_INTENT : String = "CONFIGURATION_INTENT"
const val REFRESH_TIME_INTENT : String = "REFRESH_TIME"
const val BROADCAST_LOCATION_ACTION : String = "LOCATION_ACTION";
const val BROADCAST_LOCATION_DTO : String = "LOCATION_DTO";
const val DETECTED_ACTIVITY_ACTION : String = "DETECTED_ACTIVITY_ACTION"
const val DETECTED_ACTIVITY_INTENT : String = "DETECTED_ACTIVITY_INTENT"
//const val SERVER_IP = "http://10.0.2.2:8080"
const val SERVER_IP = "http://192.168.8.3:8080"


